version: '3.3'

services:

  pygeoapi:
    
    image: geopython/pygeoapi:latest

    container_name: pygeoapi

    expose:
      - "80"

#    ports:
#     - "5000:80"

    environment:
     - SCRIPT_NAME=/pygeoapi

    volumes:
      # Map data and config into pygeoapi container
      - ./local.config.yml:/pygeoapi/local.config.yml
      - ./data:/pygeoapi/data

    labels:
      # Enable Traefik routing on overlay service network
      - "traefik.enable=true"
      - "traefik.docker.network=service-network"

      # SSL/https router
      - "traefik.http.routers.pygeoapi_https.rule=Host(`${TRAEFIK_SSL_DOMAIN}`) && PathPrefix(`/pygeoapi`)"
      - "traefik.http.routers.pygeoapi_https.entrypoints=https"
      - "traefik.http.routers.pygeoapi_https.tls=${TRAEFIK_USE_TLS}"
      - "traefik.http.routers.pygeoapi_https.tls.certresolver=${TRAEFIK_SSL_CERT_RESOLVER}"
      - "traefik.http.routers.pygeoapi_https.tls.options=my_default@file"
      - "traefik.http.routers.pygeoapi_https.middlewares=secure-headers@file"

      # local http router
      - "traefik.http.routers.pygeoapi_http.rule=Host(`localhost`) && PathPrefix(`/pygeoapi`)"
      - "traefik.http.routers.pygeoapi_http.entrypoints=http"

networks:
  default:
    external:
      name: service-network
